qcom: Define android_hardware_qtiaudio_config_defaults
We can't simply use android_hardware_audio_config_defaults because
that defaults to prefer32, which thanks to soong breaks unrelated
devices while trying to build.

Test: breakfast FP5, m, observe the following error doesn't show up:
error: vendor/osom/ingot/Android.bp:16047:1: dependency "libar-pal" of "libqtigefar" missing variant:
  os:android,image:vendor,arch:arm64_armv8-2a-dotprod_cortex-a76,link:shared
available variants:
  os:android,image:vendor,arch:arm_armv8-a_cortex-a76,link:shared

Change-Id: I8ff2bfd62f22c1a3cc11ce134098807df0bd344c